---
- name: instalace softwaru
  hosts: "{{ seznam_stanic }}"
  tasks: 
   - name: instalace
     win_chocolatey:  
      name: "{{ aplikace1 }}"
   - name: instalace
     win_chocolatey:
      name: "{{ aplikace2 }}" 
   - name: instalace
     win_chocolatey:
      name: "{{ aplikace3 }}" 
